
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver

  sql:
    init:
      schema-locations: classpath:/org/springframework/batch/core/schema-h2.sql
  batch:
    job:
      enabled: false
